container:
  image: cirrusci/flutter:latest

# check_task:
#   node_modules_cache:
#     folder: node_modules
#     fingerprint_script: cat yarn.lock
#     populate_script: yarn install
#   test_script: yarn test

flutter_tests_task:
  flutter_version:
    flutter_version_script: flutter --version
