name: Flutter Docker

on:
  workflow_dispatch:

jobs:
  flutter_checkup:
    container: cirrusci/flutter:latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Flutter Version
        run: |
          flutter --version
          ls
